### ISSUE TITLE
Where to download the candleLight driver for Windows?

### ISSUE THREAD

**Issue by boylinxing** [HubertD/cangaroo#11]
Where to download the candleLight driver for Windows?
Thanks!

**Comment by march1993** [comment]
As far as I know, the gs-usb shows up as a generic [WCID device](https://github.com/pbatard/libwdi/wiki/WCID-Devices) on Windows. You don't need driver on Windows 8 or later. The packets transfered over USB wire are defined [here](https://github.com/HubertD/cangaroo/tree/master/src/driver/CandleApiDriver/api).

**Comment by rusefillc** [comment]
@march1993 you are right but there is also https://github.com/HubertD/candle_dll/

is it that candle.dll is supposed to provide a higher level API comparing with just direct USB access?

A bit odd to see this cangaroo here not using https://github.com/HubertD/candle_dll as a git submodule but having a copy (?) of the source code?

**Comment by Elmue** [comment]
rusefillc: If you look into the sourcecode you will see that there are different versions of the code which Cangaroo uses to connect over WinUsb:

Cangaroo uses this code (compiled into the main EXE):
https://github.com/normaldotcom/cangaroo/tree/master/src/driver/CandleApiDriver/api

HubertD uses this code (compiled into Candle.dll):
https://github.com/HubertD/candle_dll/tree/master/src

And Candle.NET uses this code (compiled into Candle.dll):
https://github.com/elliotwoods/Candle.NET/tree/main/Candle

Compare them and you will see that they are all the same code with small modifications.
And Cangaroo does not use a DLL because the code is compiled into the EXE.

**Comment by prounlocks** [comment]
Okay but in win 11 after flashing Candlelight - i have 2 unknown devices and no drivers found. Okay i used zadik to install libusbk but cangaroo-win32-ccdcb64cant find any interface now. Only with COM port scl fw working

**Comment by prounlocks** [comment]
STM32G431 controller.  
![image](https://github.com/user-attachments/assets/295b4036-61fe-4337-a602-0c0b2c44afb7)
here is offered FW.
After flashing 
![image](https://github.com/user-attachments/assets/8409cb2d-f7bf-4751-9bdd-8c896233d791)

**Comment by prounlocks** [comment]
I have tried 7, 10, 11 windows - same result. MKS CANABLE 2.0 PRO S -  can't install drivers automatically.  After ZADIG tool - installed, but not working with CANGAROO

**Comment by Elmue** [comment]
This article says clearly that a driver is not required for a WinUSB device:
https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/automatic-installation-of-winusb

Install USBLyzer from www.usblyzer.com and study the descriptor. What do you see ?

And what about the SLCAN firmware?
Does this work for you ?
You should see a COM port.

Why do you want to use the Candlelight firmware ?
SLCAN is easier.

**Comment by inonez** [comment]
> I have tried 7, 10, 11 windows - same result. MKS CANABLE 2.0 PRO S - can't install drivers automatically. After ZADIG tool - installed, but not working with CANGAROO

I had the same problem as you, did you solve it later? @prounlocks

**Comment by pas4ik** [comment]
I have this problem too, cangaroo (both beta and legacy) working with slcan, but not find candlelight device (libusb / libusbK both). and what is Unknown device?
* I try now legacy with slcan, it not find COM port. So legacy all not working

**Comment by justmeDPC** [comment]
I just installed candlelight on my MKS Canable 2.0 Pro and have the exact same problem as in the pictures  from december 8, 2024 showed by @prounlocks.

**Comment by Bwanna** [comment]
Having same issue with Jhoinrch RH02 USB-CAN device.  Is recognized as slcan with fw installed, but is not recognized as socketcan with candlelight fw installed.  Actually with candlelight fw device doesn't even register with device manager Win11

**Comment by justmeDPC** [comment]
if you need a USB-CAN device with candlelight firmware, just buy one which has already [Candlelight firmware installed like this one](https://www.aliexpress.com/item/1005004879845944.html?spm=a2g0o.order_list.order_list_main.10.a8771802LGMtWO) V1.0 or this one[ (isolated version 1.1 PRO)](https://www.aliexpress.com/item/1005006032351087.html?spm=a2g0o.order_list.order_list_main.20.a8771802LGMtWO) I have both now. Not for Cangaroo but for another program.

The only thing... from 5 computers only 2 (really old) detected them and windows installed the driver. They should show up in device manager under usb ports if a driver is available.
For the computer i needed them, that pc showed "no driver installed" in device manager. So i used Zadig to install a windows driver. You need to install driver for both the instances you see in device manager for the canable device. Start Zadig select the canable name and just install the windows driver which should be already selected next to green arrow (WinUSB V6.1.7600.16385).

Then you do the same for the second Canable name, if you don't see the second name anymore, click "options" and select "show all devices" be careful to select only the correct second canable name and not the one you already did!  Afterwards you should find the canable device under usb ports if all went well.

**Comment by Elmue** [comment]
First of all: Your are not alone with this problem.

@march1993: 
> As far as I know, the gs-usb shows up as a generic WCID device on Windows.

This is correct for the old CANable 1.0 devices where this is implemented correctly.
But it does not apply to the firmware **ba6b1dd** on canable.io for the CANable 2.0 where this is **NOT IMPLMENTED**.
The firmware that you find in the web updater for the CANable 2.0 is **GARBAGE**.

The automatic driver installation on Windows works only if the device answers correctly to the Microsoft OS Descriptor Request. This is not difficult and works in the old CANable 1.0.

But the firmware with version **ba6b1dd** for the CANable 2.0 does not respond **AT ALL** to this request, so Windows does not install a driver automatically. You see 2 unknown devices in Device Manager. Not because Windows does not work, but because this firmware is buggy **CRAP**. This firmware has never been finished. Also this firmware does not implement CAN FD. I don't understand why canable.io uploads this at all.

@prounlocks
> After ZADIG tool - installed, but not working with CANGAROO

There you have 2 problems.

**Zadig** is another sloppy software that is totally useless to install a CANable where the MS OS descriptor request is not working. The only thing that Zadig does is to install the WinUSB driver for your device so in Device Manager it does not show an error symbol anymore. 

But it is not enough to assign the WinUSB driver to the CANable. It is indispensable that the CANable is registered with the correct GUID in the registry which MUST be **{c15b4308-04d3-11e6-b3ea-6057189e6443}**.
But Zadig is so stupid that it installs the CANable with any random GUID that is different each time you use Zadig.
If Zadig would have been programmed by a more intelligent person it would ask you with which GUID you want to install the device instead of using any useless random GUID. So no surprise that you get nowhere with Zadig.

@prounlocks
> After ZADIG tool - installed, but not working with CANGAROO

And your second problem is **Cangaroo** itself. Cangaroo is full of bugs that get never fixed in 6 years. Cangaroo is a dead project.

@justmeDPC
> if you need a USB-CAN device with candlelight firmware, just buy one which has already Candlelight firmware installed 

This advice is only useful if you do not plan to use CAN FD.
All the boards that come with Candlelight already installed have an old processor without CAN FD support. I would say that buying a CANable 1.0 without CAN FD support is not a good advice.

I studied all the Candlelight projects on Github. Until now there is **no correctly working Candlelight firmware** for the CANable 2.0 with CAN FD support.
It does not exist !

And even the old Candlelight firmware that works for CANable 1.0 reduces the possible USB throughput because of design errors. Instead of designing a fast protocol that passes the traffic on CAN bus as fast as possible to the computer they use a very inefficient protocol.
______________________________________

It is a **shame** that so many people dump a code on Github that is not working, that has misdesigns, that has very **severe bugs** and then they do not care to fix these bugs in several years.
The result is that other people, like you all here, **waste their time** with this crap.

And most projects on Github do not even offer the firmware in binary form. You must first install a compiler, learn how to use it and then find a way how to get that firmware onto you CANable! 

I was so bored about all this buggy low quality that you get for free on Github, that I finally wrote a **completely new firmware** for the CANable 2.0.

Your problems are all solved now !
You can now install the new CANable 2.5 firmware from ElmüSoft that has been tested on the CANable from MKS Makerbase with the STM32G431 processor. It works with CAN FD data baudrates up to 10 Mbaud.

<img width="284" height="104" alt="Image" src="https://github.com/user-attachments/assets/c1274fb5-a4c0-4634-9679-bf677fe18c30" />

I worked **three months full time** on this huge project and I offer the first Candlelight firmware ever that works on a CANable 2.0, that supports CAN FD, that installs instantly a driver on Windows (it takes less than 1 second to install the driver).

I even designed a new protocol for Candlelight that **optimizes the USB throughput** to the maximum that is possible. However my new firmware is still 100% backward compatible with legacy software.

But this is not all.
The new firmware would be useless for the majority of users, who are not programmers, if they cannot load it on their CANable. Therefore I wrote a new Firmware Updater that uploads a firmware to any STM32 processor with one click.

<img width="577" height="484" alt="Image" src="https://github.com/user-attachments/assets/c638e8e4-19ca-4d0a-b0bb-e9f73728ea16" />

And there is no need anymore to use the dead project Cangaroo to communicate with your CANable. You can now use the CAN Terminal in **HUD ECU Hacker**. HUD ECU Hacker is like the swiss knife for CAN bus. It has all you need. You can write logfiles, you can send command manually to CAN bus, you can send logfiles to CAN bus, you can even write macro scripts that simulate any device on CAN bus.
The CAN terminal also works with legacy CANable 1.0 devices.

<img width="698" height="707" alt="Image" src="https://github.com/user-attachments/assets/5158dc11-1fe8-496c-8d4f-9ba5ef5ecd35" />

I wrote a very detailed manual where you find all the information that you need:
https://netcult.ch/elmue/CANable%20Firmware%20Update

**Comment by justmeDPC** [comment]
Looks all great but this seems to be the same: quote "And most projects on Github do not even offer the firmware in binary form. You must first install a compiler, learn how to use it and then find a way how to get that firmware onto you CANable!"

I looked at your github link but seems we still need to compile it ourself to get the canable bin file. For non coders that is  asking for failures.
Some time back i got my canable v2 with candlelight finally running after a lot of trial and error i could download it to the board using that old DOS dfu-utils.

I was looking on your webpage which IS interesting to read and  looked for a canable V2 bin but could not find one. Great it can be uploaded via HUD ECU Hacker integrated firmware updater but where are the bin file(s)? And where to find a download for Hud Ecu hacker ?


Best regards,
justmeDPC

**Comment by Elmue** [comment]
@justmeDPC
The problem is that you did not read my long description!
All the answers are there. 
You must only spend a few minutes of your time to read it!

There is the link and there is the description how to upload the firmware.

<img width="755" height="433" alt="Image" src="https://github.com/user-attachments/assets/ee731b81-4c71-49c2-aa1b-5555d5706d0a" />

Is this too difficult to understand?

If I would offer the BIN file on my homepage it would be COMPLETELY uselss!
To upload the firmware to a CANable you need:
1.) a software that can communicate over the DFU protocol with the STM32 processor
2.) To use this software you must first install the driver from ST Microelectronics
3.) You must know the exact memory address in the processor where to upload the firmware to.
4.) Then you need a software that can communicate over the CANable with the CAN bus.

The people would write me emails: Now I downloaded the BIN file and how do I get it on my CANable ?" 

Therefore I implemented a ready to use solution which does all this with one click
It's name is HUD ECU Hacker. It is like the swiss knife for CAN bus.
There are 4 different firmware versions installed with HUD ECU Hacker.

By purpose the firmware is NOT in **BIN** files.
The firmware is in **DFU** files which contain all the information that the firmware updater needs.
In a BIN file this information is not present. You would have to enter all this additional information manually. 
I explain all this in the manual. You must only read it!

One single installation and you have ALL you need.

**Comment by justmeDPC** [comment]
Thanks for the reply! The points 1 -2 -3 i already have done in the past and for point 4 i have software working with canable V2 pro. 
But now it's clear, to get the 2.5 firmware for canable i have to install Hud Ecu Hacker... And from within the firmware is available and DFU file can be downloaded to canable V2 with the integrated firmware updater. Thank you for a all in one solution.

**Comment by Elmue** [comment]
Perfect. So you can test it all. If you should find any issue, send me an email.

**Comment by justmeDPC** [comment]
Ok i installed it, and in the program using the firmware updater was easy. No need to fiddle with bootpins on Canable V2 Pro. I could just select "Enter DFU mode". Put checkmark at "Internal flash" and picked file "STM32G431 candlelight 2.5 MKS Makerbase" to upload and clicked button upload. Before i knew it, it was programmed :) Clicked "verify" => All ok.
The 3 leds on canable V2 pro are working.
For what i use the canable with there is no ECU. But via "sniffing" and "raw data" in the program i could see my can traffic. I like the fact that it shows the details from the Canable V2 Pro too. Also in the log file, i like the details above the actual data.
A big thank you for all the work you did!

**Comment by Elmue** [comment]
>A big thank you for all the work you did!

You are welcome!
I started working on HUD ECU Hacker in 2020 when the plandemic started and I had nothing else to do.
Since then I work nearly every day on my baby till today.
It is growing and growing bigger.
Nobody can imagine the tremendous work that you install with my software,

If you want to do a favor to the community of CAN bus lovers you can tell others about it.
In forums where people have problems with CAN bus you can tell them about the solution that you found.
Many people google for CAN bus and find companies that sell CAN bus adapters for $250 with a badly designed software.

**Comment by GenesisAN** [comment]
> > 非常感谢您所做的所有工作!
> 
> 欢迎你! 2020年疫情开始时,我开始着手开发HUD ECU黑客,而我却无事可做。 从那以后,我几乎每天都为宝宝工作,直到今天。 它正在不断成长并不断壮大。 没人能想象你用我的软件安装的巨大工作,
> 
> 如果你想帮到CAN公交爱好者的社区,可以向其他人透露相关信息。 在人们遇到“CAN 总线”问题的论坛中,你可以向他们介绍你找到的解决方案。 许多人通过谷歌搜索CAN总线,并找到那些使用设计不当的软件以250美元出售CAN总线适配器的公司。

I don’t even know how to put it into words—you’ve been a huge help. I’ve been struggling with these firmware issues for a long time. I use CAN tools a lot, and SLCAN never felt great when switching between Linux and Windows. I updated to your CandleLight 2.5, and now it works great with SocketCAN on Linux and with BUSMASTER on Windows.

**Comment by Elmue** [comment]
You are welcome!

**Comment by MarianneVarley** [comment]
digitalsoftwarekey
